#!/bin/bash


rofi -modi run,drun -show drun -location 1 -yoffset 50 -xoffset 15 -line-padding 4 -columns 1 -width 25 -lines 10 -padding 25 -hide-scrollbar -show-icons -drun-icon-theme "candy-icons" -font "hack 10"

